// Generated by scripts/adapter-candidates-generate.mjs. Do not edit by hand.
export const ADAPTER_CANDIDATES_BY_PAIR = {
  "dawn-valley__dusk-ridge": [
    {
      "id": "hf-nb2-axb-01",
      "label": "HF NB2 AXB 01",
      "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/hf-nb2-axb-01.png",
      "status": "rejected",
      "notes": "External dawn/dusk joins benefit from copied edge anchors, but the internal anchor-to-X boundary forms visible orange/blue vertical bands. Not selector-ready."
    },
    {
      "id": "hf-nb2-axb-02",
      "label": "HF NB2 AXB 02",
      "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/hf-nb2-axb-02.png",
      "status": "rejected",
      "notes": "Softer and lower contrast than 01, but still has obvious internal warm-to-blue banding and no pixel-preserved anchors. Not selector-ready."
    },
    {
      "id": "gpt-axb-01",
      "label": "GPT AXB 01",
      "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01.png",
      "status": "partial",
      "notes": "Strongest standalone semantic AXB transition so far, with a natural warm-to-cool mountain bridge. Not accepted as final because outer anchors are not pixel-exact after GPT generation and resize."
    },
    {
      "id": "gpt-axb-01-xonly",
      "label": "GPT AXB 01 X-only",
      "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-xonly.png",
      "status": "partial",
      "notes": "Outer plate-facing anchors are exact, but hard X-only compositing creates visible internal anchor-to-X discontinuities. Useful diagnostic, not accepted final adapter."
    }
  ]
} as const;
