// Generated by scripts/adapter-candidates-generate.mjs. Do not edit by hand.
export const ADAPTER_CANDIDATES_BY_PAIR = {
  "dawn-valley__dusk-ridge": {
    "activeForReview": "photoshop-test1",
    "candidates": [
      {
        "id": "hf-nb2-axb-01",
        "label": "HF NB2 AXB 01",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/hf-nb2-axb-01.png",
        "status": "rejected",
        "notes": "External dawn/dusk joins benefit from copied edge anchors, but the internal anchor-to-X boundary forms visible orange/blue vertical bands. Not selector-ready.",
        "reviewSummary": null
      },
      {
        "id": "hf-nb2-axb-02",
        "label": "HF NB2 AXB 02",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/hf-nb2-axb-02.png",
        "status": "rejected",
        "notes": "Softer and lower contrast than 01, but still has obvious internal warm-to-blue banding and no pixel-preserved anchors. Not selector-ready.",
        "reviewSummary": null
      },
      {
        "id": "gpt-axb-01",
        "label": "GPT AXB 01",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01.png",
        "status": "partial",
        "notes": "Strongest standalone semantic AXB transition so far, with a natural warm-to-cool mountain bridge. Not accepted as final because outer anchors are not pixel-exact after GPT generation and resize.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 194,
          "rightOuterAnchorMaxDiff": 100,
          "internalJoinVerdict": "Natural X concept, but outer anchors are not exact."
        }
      },
      {
        "id": "gpt-axb-01-xonly",
        "label": "GPT AXB 01 X-only",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-xonly.png",
        "status": "partial",
        "notes": "Outer plate-facing anchors are exact, but hard X-only compositing creates visible internal anchor-to-X discontinuities. Useful diagnostic, not accepted final adapter.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact outer anchors; hard A-X / X-B cuts are visible."
        }
      },
      {
        "id": "gpt-axb-01-soft64",
        "label": "GPT AXB 01 soft64",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-soft64.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; internal blend still reads hard."
        }
      },
      {
        "id": "gpt-axb-01-soft128",
        "label": "GPT AXB 01 soft128",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-soft128.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; internal blend is reduced but still visible."
        }
      },
      {
        "id": "gpt-axb-01-soft256",
        "label": "GPT AXB 01 soft256",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-soft256.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; smoothest pre-sweep strict-X candidate."
        }
      },
      {
        "id": "gpt-axb-01-linear128",
        "label": "GPT AXB 01 linear 128",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-linear128.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; narrower blend leaves more internal banding."
        }
      },
      {
        "id": "gpt-axb-01-linear192",
        "label": "GPT AXB 01 linear 192",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-linear192.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; narrower blend leaves more internal banding."
        }
      },
      {
        "id": "gpt-axb-01-linear256",
        "label": "GPT AXB 01 linear 256",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-linear256.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; balanced sweep candidate, similar to soft256."
        }
      },
      {
        "id": "gpt-axb-01-linear384",
        "label": "GPT AXB 01 linear 384",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-linear384.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; wider blend reduces right band but muddies left A-X transition."
        }
      },
      {
        "id": "gpt-axb-01-linear512",
        "label": "GPT AXB 01 linear 512",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-linear512.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; wider blend reduces right band but muddies left A-X transition."
        }
      },
      {
        "id": "gpt-axb-01-smoothstep128",
        "label": "GPT AXB 01 smoothstep 128",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-smoothstep128.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; narrower blend leaves more internal banding."
        }
      },
      {
        "id": "gpt-axb-01-smoothstep192",
        "label": "GPT AXB 01 smoothstep 192",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-smoothstep192.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; narrower blend leaves more internal banding."
        }
      },
      {
        "id": "gpt-axb-01-smoothstep256",
        "label": "GPT AXB 01 smoothstep 256",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-smoothstep256.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; balanced sweep candidate, similar to soft256."
        }
      },
      {
        "id": "gpt-axb-01-smoothstep384",
        "label": "GPT AXB 01 smoothstep 384",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-smoothstep384.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; wider blend reduces right band but muddies left A-X transition."
        }
      },
      {
        "id": "gpt-axb-01-smoothstep512",
        "label": "GPT AXB 01 smoothstep 512",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-smoothstep512.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; wider blend reduces right band but muddies left A-X transition."
        }
      },
      {
        "id": "gpt-axb-01-cosine128",
        "label": "GPT AXB 01 cosine 128",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-cosine128.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; narrower blend leaves more internal banding."
        }
      },
      {
        "id": "gpt-axb-01-cosine192",
        "label": "GPT AXB 01 cosine 192",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-cosine192.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; narrower blend leaves more internal banding."
        }
      },
      {
        "id": "gpt-axb-01-cosine256",
        "label": "GPT AXB 01 cosine 256",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-cosine256.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; balanced sweep candidate, similar to soft256."
        }
      },
      {
        "id": "gpt-axb-01-cosine384",
        "label": "GPT AXB 01 cosine 384",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-cosine384.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; wider blend reduces right band but muddies left A-X transition."
        }
      },
      {
        "id": "gpt-axb-01-cosine512",
        "label": "GPT AXB 01 cosine 512",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/gpt-axb-01-cosine512.png",
        "status": "partial",
        "notes": "Strictly preserves original A/B anchors and blends only inside X. Review at blend=0 before accepting.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Exact anchors; wider blend reduces right band but muddies left A-X transition."
        }
      },
      {
        "id": "manual-smoke-identity",
        "label": "Manual smoke identity",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/manual-smoke-identity.png",
        "status": "rejected",
        "notes": "External output was treated as X source only. Original A/B anchors were composited back from the manual work canvas; outside-X diff is verified at 0.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Manual X-only import; exact A/B anchors restored. Inspect A-X and X-B at blend=0."
        }
      },
      {
        "id": "photoshop-test1",
        "label": "Photoshop test 1",
        "imageUrl": "/panos/adapter-candidates/dawn-valley__dusk-ridge/photoshop-test1.png",
        "status": "partial",
        "notes": "External output was treated as X source only. Original A/B anchors were composited back from the manual work canvas; outside-X diff is verified at 0.",
        "reviewSummary": {
          "leftOuterAnchorMaxDiff": 0,
          "rightOuterAnchorMaxDiff": 0,
          "internalJoinVerdict": "Manual X-only import; exact A/B anchors restored. Inspect A-X and X-B at blend=0."
        }
      }
    ]
  }
} as const;
